### ISSUE TITLE
Como integrar com slack

### ISSUE THREAD

**Issue by dexterpedro** [badtuxx/giropops-monitoring#8]
Pessoal, boa tarde...
Estou a uns dias tentando implementar o projeto... estou querendo usar o slack e não o rocket chat...
nos videos do youtube vocês ensinam como o slack.. mas não consigo .... acho que mudaram algo no alertmanager que o slack n ta consigurando sei la...
o alertmanager não sobe... 
sou novo em todo esse lance de docker monitoramento e etc... precisava de um help...
Desde já agradeço... e o projeto ta muito bom.
Valeu...

**Comment by terasaka** [comment]
Fala ai @dexterpedro, qual o log do alertmanager?

`docker service logs giropops_alertmanager`

E como vc configurou as informações do slack no conf/alertmanager/config.yml ?

Da uma olhada nesse exemplo:

```YML
route:
    receiver: 'slack'

receivers:
    - name: 'slack'
      slack_configs:
          - send_resolved: true
            text: "{{ .CommonAnnotations.description }}"
            username: 'alertmanager'
            channel: '#monitoramento'
            api_url: 'https://hooks.slack.com/services/TOKEN'
```
